# syntax=docker/dockerfile:1

# ベースイメージは Ruby
ARG RUBY_VERSION=3.3.6
FROM ruby:$RUBY_VERSION-slim AS base

WORKDIR /rails

# 開発に必要な基本パッケージをインストール
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    curl \
    libjemalloc2 \
    libvips \
    postgresql-client \
    libbrotli1 \
    libpng16-16 \
    libfreetype6 \
    fonts-dejavu-core \
    fontconfig-config \
    libfontconfig1 \
    libaom3 \
    libdav1d6 \
    libde265-0 \
    libnuma1 && \
    ln -s /usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2 /usr/local/lib/libjemalloc.so && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle" \
    LD_PRELOAD="/usr/local/lib/libjemalloc.so"

# ビルド用ステージ
FROM base AS build

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    libyaml-dev \
    node-gyp \
    pkg-config \
    python-is-python3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Node.js と Yarn のインストール
ARG NODE_VERSION=20.19.6
ARG YARN_VERSION=1.22.22
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g yarn@$YARN_VERSION && \
    rm -rf /tmp/node-build-master

# Gem のインストール
COPY Gemfile Gemfile.lock vendor ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile -j 1 --gemfile

# Node モジュールのインストール
COPY package.json yarn.lock ./
RUN yarn install --immutable

# アプリコードのコピー
COPY . .

# bootsnap のプリコンパイル
RUN bundle exec bootsnap precompile -j 1 app/ lib/

# 開発用ユーザー作成
RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash
USER 1000:1000

# エントリーポイント
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# ポート設定
EXPOSE 3000

# デフォルトコマンド（Railsサーバー起動）
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
